import type { Metadata } from "next";
import { Unbounded, Red_Hat_Display } from "next/font/google";
import "./globals.css";
import React from "react";
import { Toaster } from "react-hot-toast";

const unbounded = Unbounded({
  variable: "--unbounded",
  subsets: ["latin"],
});

const redHatDisplay = Red_Hat_Display({
  variable: "--red-hat-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "WorkSphere",
    template: "WorkSphere - %s",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {children}
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
