import type { Metadata } from "next";
import { Unbounded, Red_Hat_Display } from "next/font/google";
import "./globals.css";
import React from "react";

const unbounded = Unbounded({
    variable: "--unbounded",
    subsets: ['latin']
});

const redHatDisplay = Red_Hat_Display({
    variable: "--red-hat-display",
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: {
        default: "WorkWave",
        template: "WorkWave - %s"
    },
    description: "Generated by create next app",
    icons: {
        icon: "/logo.svg"
    }
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${unbounded.variable} ${redHatDisplay.variable}`}
        >
            {children}
        </html>
    );
}
